# include ~/.config/omarchy/current/theme/kitty.conf

# Font
font_family JetBrainsMonoNL Nerd Font Mono
bold_italic_font auto
font_size 11.25

# Window
window_padding_width 0
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab
map ctrl+shift+q close_tab
map ctrl+shift+t new_tab

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_align center
tab_bar_edge top
tab_bar_style separator
tab_bar_min_tabs 1
tab_powerline_style slanted
tab_separator " | "
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"

# Color
foreground #cdd6f4
background #1e1e2e
selection_foreground #1e1e2e
selection_background #f5e0dc

cursor #f5e0dc
cursor_text_color #1e1e2e

active_border_color #89b4fa
active_tab_foreground #89b4fa
active_tab_background #1e1e2e
active_tab_font_style   bold-italic
inactive_tab_foreground #bac2de
inactive_tab_background #1e1e2e

color0 #45475a
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #f5c2e7
color6 #94e2d5
color7 #bac2de
color8 #585b70
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #a6adc8
